spring:
  webflux:
    base-path: /api
  application:
    name: handwriting-todo-be
  ai:
    retry:
      max-attempts: 1
    ollama:
      base-url: "${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}"
      chat:
        options:
          model: qwen2.5vl:7b
          timeout: 360s
vast:
  api:
    token: "${VAST_API_TOKEN:}"